### PR TITLE
Update Live CRD with new limitRequestRatio type

### PR DESCRIPTION
**Pull request by wbrefvem**

### CODE REVIEW

**Comment by jgustie** [comment]
Is this just copying [the original](https://github.com/gramLabs/optimize-live-controller/blob/main/config/crd/bases/optimize.stormforge.io_lives.yaml) over?

**Comment by bradbeam** [comment]
just to note, we'll hold off on merging this until we're ready to release 0.7.2. we'll use this branch (`ol072`) as the staging area for the next release

**Comment by wbrefvem** [comment]
@jgustie Yes.

**Comment by wbrefvem** [comment]
@bradbeam I can close this if that's what makes sense.

**Review by bradbeam — APPROVED** [review]

**Pull request merged**
